// traduc.js
window.frasesApp = {
    phrases: [


  { "english": "They broke into the old mansion at midnight last Saturday night.", "spanish": "Irrumpieron en la vieja mansión a medianoche el sábado pasado." },
  { "english": "She waited for the train near the station in heavy rain.", "spanish": "Ella esperó el tren cerca de la estación bajo fuerte lluvia." },
  { "english": "I found a wallet lying on the sidewalk near the corner.", "spanish": "Encontré una cartera tirada en la acera cerca de la esquina." },
  { "english": "We traveled across the country by train during summer vacation last year.", "spanish": "Viajamos por el país en tren durante las vacaciones del año pasado." },
  { "english": "He always brings his guitar when we go camping in July.", "spanish": "Él siempre lleva su guitarra cuando vamos de campamento en julio." },
  { "english": "My parents moved to a small village surrounded by pine trees.", "spanish": "Mis padres se mudaron a un pueblo pequeño rodeado de pinos." },
  { "english": "They rescued the dog that had fallen into the frozen river.", "spanish": "Rescataron al perro que había caído en el río congelado." },
  { "english": "She cooked dinner using only vegetables from her backyard garden today.", "spanish": "Cocinó la cena usando solo verduras de su jardín trasero hoy." },
  { "english": "The teacher explained the equation using colorful markers on the whiteboard.", "spanish": "La maestra explicó la ecuación usando marcadores de colores en el pizarrón." },
  { "english": "He forgot his umbrella and got soaked walking home from school.", "spanish": "Olvidó su paraguas y se empapó caminando a casa desde la escuela." },
  { "english": "They built a treehouse together over the summer in their backyard.", "spanish": "Construyeron una casa del árbol juntos durante el verano en su patio." },
  { "english": "We watched fireworks explode over the river during the national celebration.", "spanish": "Vimos fuegos artificiales estallar sobre el río durante la celebración nacional." },
  { "english": "I lost my passport while traveling through the mountains with my friends.", "spanish": "Perdí mi pasaporte mientras viajaba por las montañas con mis amigos." },
  { "english": "The baby smiled when she saw the butterfly land on her.", "spanish": "La bebé sonrió cuando vio aterrizar la mariposa sobre ella." },
  { "english": "He drew a map showing all the secret paths in town.", "spanish": "Dibujó un mapa que muestra todos los caminos secretos del pueblo." },
  { "english": "She danced barefoot in the rain after hearing her favorite song.", "spanish": "Bailó descalza bajo la lluvia tras escuchar su canción favorita." },
  { "english": "They planted flowers and painted the fence on a sunny morning.", "spanish": "Plantaron flores y pintaron la cerca en una mañana soleada." },
  { "english": "We spent the entire weekend cleaning the attic and organizing boxes.", "spanish": "Pasamos todo el fin de semana limpiando el ático y organizando cajas." },
  { "english": "He fixed his bicycle using tools borrowed from the friendly neighbor.", "spanish": "Arregló su bicicleta usando herramientas prestadas por el vecino amigable." },
  { "english": "I received your letter yesterday and read it three times already.", "spanish": "Recibí tu carta ayer y ya la leí tres veces." },
  { "english": "The wind knocked down the tree that blocked the narrow road.", "spanish": "El viento derribó el árbol que bloqueaba el camino estrecho." },
  { "english": "We saw dolphins jumping near the boat during our morning cruise.", "spanish": "Vimos delfines saltando cerca del bote durante nuestro crucero matutino." },
  { "english": "She baked a chocolate cake and shared it with her classmates.", "spanish": "Horneó un pastel de chocolate y lo compartió con sus compañeros." },
  { "english": "He slipped on the ice and dropped all the grocery bags.", "spanish": "Resbaló en el hielo y dejó caer todas las bolsas del supermercado." },
  { "english": "They explored the caves with flashlights and helmets on their heads.", "spanish": "Exploraron las cuevas con linternas y cascos en la cabeza." },
  { "english": "I sent the invitation by mail and received your answer today.", "spanish": "Envié la invitación por correo y recibí tu respuesta hoy." },
  { "english": "We visited the museum last weekend and learned about ancient civilizations.", "spanish": "Visitamos el museo el fin de semana pasado y aprendimos sobre civilizaciones antiguas." },
  { "english": "The sun disappeared behind the hills just before we arrived there.", "spanish": "El sol desapareció detrás de las colinas justo antes de que llegáramos." },
  { "english": "He painted a landscape using only shades of blue and white.", "spanish": "Pintó un paisaje usando solo tonos de azul y blanco." },
  { "english": "She left her notebook on the bench and ran to class.", "spanish": "Dejó su cuaderno en la banca y corrió a clase." },
  { "english": "They listened to the storm while sitting quietly on the porch.", "spanish": "Escucharon la tormenta mientras se sentaban en silencio en el porche." },
  { "english": "I saved your message and plan to reply after dinner tonight.", "spanish": "Guardé tu mensaje y planeo responder después de la cena esta noche." },
  { "english": "We took a photo together under the cherry trees in bloom.", "spanish": "Nos tomamos una foto juntos bajo los cerezos en flor." },
  { "english": "The cat climbed the curtains and got stuck near the ceiling.", "spanish": "El gato trepó las cortinas y quedó atrapado cerca del techo." },
  { "english": "He drove through the storm and reached home safely before midnight.", "spanish": "Condujo a través de la tormenta y llegó a casa sano antes de medianoche." },
  { "english": "They sent postcards from every city they visited during their trip.", "spanish": "Enviaron postales desde cada ciudad que visitaron durante su viaje." },
  { "english": "She picked up seashells and placed them gently in her bag.", "spanish": "Recogió conchas marinas y las colocó cuidadosamente en su bolsa." },
  { "english": "I hid the birthday present under the bed before she arrived.", "spanish": "Escondí el regalo de cumpleaños debajo de la cama antes de que llegara." },
  { "english": "We followed the path through the forest until reaching the lake.", "spanish": "Seguimos el sendero por el bosque hasta llegar al lago." },
  { "english": "He heard footsteps behind him while walking alone in the woods.", "spanish": "Escuchó pasos detrás de él mientras caminaba solo por el bosque." },
  { "english": "The book she lent me had notes written on every page.", "spanish": "El libro que me prestó tenía notas escritas en cada página." },
  { "english": "They painted the room blue and added stars to the ceiling.", "spanish": "Pintaron la habitación de azul y añadieron estrellas al techo." },
  { "english": "I dropped my phone into the fountain while feeding the ducks.", "spanish": "Dejé caer mi teléfono en la fuente mientras alimentaba a los patos." },
  { "english": "He saw a shooting star and made a secret birthday wish.", "spanish": "Vio una estrella fugaz e hizo un deseo secreto de cumpleaños." },
  { "english": "She covered the cake with strawberries and a thick layer cream.", "spanish": "Cubrió el pastel con fresas y una capa gruesa de crema." },
  { "english": "We danced around the fire and sang songs in the dark.", "spanish": "Bailamos alrededor del fuego y cantamos canciones en la oscuridad." },
  { "english": "He wrapped the gift carefully and tied it with blue ribbon.", "spanish": "Envolvió el regalo cuidadosamente y lo ató con una cinta azul." },
  { "english": "The thunder scared the children who were hiding under the table.", "spanish": "El trueno asustó a los niños que se escondían bajo la mesa." },
  { "english": "They carried the old piano upstairs using ropes and pure determination.", "spanish": "Subieron el viejo piano usando cuerdas y pura determinación." },
  { "english": "She forgot her umbrella and got soaked in the rain.", "spanish": "Olvidó su paraguas y se empapó bajo la lluvia." },
  { "english": "We arrived late because of the heavy traffic.", "spanish": "Llegamos tarde por el tráfico pesado." },
  { "english": "He always drinks coffee before starting work.", "spanish": "Siempre toma café antes de empezar a trabajar." },
  { "english": "The cat jumped onto the couch and fell asleep.", "spanish": "El gato saltó al sofá y se quedó dormido." },
  { "english": "My brother plays the guitar very well.", "spanish": "Mi hermano toca la guitarra muy bien." },
  { "english": "They went to the mountains to escape the heat.", "spanish": "Fueron a las montañas para escapar del calor." },
  { "english": "I lost my keys at the supermarket.", "spanish": "Perdí mis llaves en el supermercado." },
  { "english": "She painted the walls a bright yellow.", "spanish": "Pintó las paredes de un amarillo brillante." },
  { "english": "The movie started twenty minutes late.", "spanish": "La película comenzó veinte minutos tarde." },
  { "english": "He doesn’t like vegetables, especially broccoli.", "spanish": "No le gustan los vegetales, especialmente el brócoli." },
  { "english": "We found an old map in the attic.", "spanish": "Encontramos un mapa viejo en el ático." },
  { "english": "She’s learning to bake bread from scratch.", "spanish": "Está aprendiendo a hornear pan desde cero." },
  { "english": "He fell asleep with the TV still on.", "spanish": "Se quedó dormido con la televisión encendida." },
  { "english": "The dog barked all night during the storm.", "spanish": "El perro ladró toda la noche durante la tormenta." },
  { "english": "They watched the sunrise from the beach.", "spanish": "Vieron el amanecer desde la playa." },
  { "english": "I need to charge my phone before we leave.", "spanish": "Necesito cargar mi teléfono antes de salir." },
  { "english": "She bought a gift for her best friend.", "spanish": "Compró un regalo para su mejor amiga." },
  { "english": "He doesn’t remember what he said last night.", "spanish": "No recuerda lo que dijo anoche." },
  { "english": "They built a treehouse in the backyard.", "spanish": "Construyeron una casa del árbol en el patio trasero." },
  { "english": "She cleaned the windows until they sparkled.", "spanish": "Limpió las ventanas hasta que brillaron." },
  { "english": "I couldn’t sleep because of the noise.", "spanish": "No pude dormir por el ruido." },
  { "english": "We danced all night at the wedding.", "spanish": "Bailamos toda la noche en la boda." },
  { "english": "The teacher gave us a lot of homework.", "spanish": "La maestra nos dio mucha tarea." },
  { "english": "He fixed the bike by himself.", "spanish": "Arregló la bicicleta él solo." },
  { "english": "They waited outside in the cold.", "spanish": "Esperaron afuera en el frío." },
  { "english": "She wrote a letter to her grandmother.", "spanish": "Escribió una carta a su abuela." },
  { "english": "I forgot to bring my wallet.", "spanish": "Olvidé traer mi cartera." },
  { "english": "He ran five kilometers this morning.", "spanish": "Corrió cinco kilómetros esta mañana." },
  { "english": "They were surprised by the announcement.", "spanish": "Se sorprendieron por el anuncio." },
  { "english": "She likes to read before going to bed.", "spanish": "Le gusta leer antes de acostarse." },
  { "english": "We had dinner on the rooftop terrace.", "spanish": "Cenamos en la terraza de la azotea." },
  { "english": "He broke the vase while cleaning.", "spanish": "Rompió el jarrón mientras limpiaba." },
  { "english": "The kids are playing hide and seek.", "spanish": "Los niños están jugando a las escondidas." },
  { "english": "She always arrives early to work.", "spanish": "Siempre llega temprano al trabajo." },
  { "english": "I saw a shooting star last night.", "spanish": "Vi una estrella fugaz anoche." },
  { "english": "They forgot their tickets at home.", "spanish": "Olvidaron sus boletos en casa." },
  { "english": "He didn’t answer any of my messages.", "spanish": "No respondió ninguno de mis mensajes." },
  { "english": "The ice cream melted in the sun.", "spanish": "El helado se derritió al sol." },
  { "english": "She tripped and spilled her drink.", "spanish": "Tropezó y derramó su bebida." },
  { "english": "We watched a documentary about whales.", "spanish": "Vimos un documental sobre ballenas." },
  { "english": "He made a mistake on the report.", "spanish": "Cometió un error en el informe." },
  { "english": "They visited a castle during the trip.", "spanish": "Visitaron un castillo durante el viaje." },
  { "english": "She needs to study for the exam.", "spanish": "Necesita estudiar para el examen." },
  { "english": "The bus arrived later than expected.", "spanish": "El autobús llegó más tarde de lo esperado." },
  { "english": "I heard a strange noise in the kitchen.", "spanish": "Escuché un ruido extraño en la cocina." },
  { "english": "He bought new shoes for the race.", "spanish": "Compró zapatos nuevos para la carrera." },
  { "english": "We met at the café near the station.", "spanish": "Nos encontramos en la cafetería cerca de la estación." },
  { "english": "She forgot to water the plants.", "spanish": "Olvidó regar las plantas." },
  { "english": "He laughed so hard that he cried.", "spanish": "Se rió tanto que lloró." }
],

    // Include the contractions mapping here
    contractions: {
        "i'm": "i am",
        "you're": "you are",
        "he's": "he is",
        "she's": "she is",
        "it's": "it is",
        "we're": "we are",
        "they're": "they are",
        "i've": "i have",
        "you've": "you have",
        "we've": "we have",
        "they've": "they have",
        "i'll": "i will",
        "you'll": "you will",
        "he'll": "he will",
        "she'll": "she will",
        "it'll": "it will",
        "we'll": "we will",
        "they'll": "they will",
        "isn't": "is not",
        "aren't": "are not",
        "wasn't": "was not",
        "weren't": "were not",
        "hasn't": "has not",
        "haven't": "have not",
        "hadn't": "had not",
        "won't": "will not",
        "wouldn't": "would not",
        "don't": "do not",
        "doesn't": "does not",
        "didn't": "did not",
        "can't": "cannot",
        "couldn't": "could not",
        "shouldn't": "should not",
        "mightn't": "might not",
        "mustn't": "must not",
        "take off": "takeoff",
        "takeoff": "take off"
    },

    obtenerAleatoria: function() {
        return this.phrases[Math.floor(Math.random() * this.phrases.length)];
    }
};
